name: 'Test Report'
on:
  workflow_run:
    workflows: ['Node.js CI']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Mocha Tests
          path: '*.json'
          reporter: mocha-json
